### ISSUE TITLE
Naked Single Does Not Update Notepad

### ISSUE THREAD

**Issue by jfkonecn** [Licktopia/ChampionsOfSudoku2#15]
After clicking the naked single button the all of the notes remain the same.

**Comment by MKormann** [comment]
Yeah the reason the single doesn't update anything is because it calls a different function than the other hints, since it's the only one that actually fills a square in.

Right now all of the other buttons call update notepad when clicked so we can see them work, which is why the board changes so much, but Jeff and I had talked about removing that too for the release.  I think we talked early on in the project about only executing hints on the notepad that the player has filled out, which I think still makes the most sense.

**Comment by MKormann** [comment]
Putting in a "Fill Notepad" hint/strat to auto fill in the notepad for the player might be worth considering, too.

Also I didn't mean to close this issue haha, I just can't reopen it.

**Comment by MKormann** [comment]
Fixed as part of Issue #8
