### ISSUE TITLE
Scoring things

### ISSUE THREAD

**Issue by Licktopia** [Licktopia/ChampionsOfSudoku2#20]
1. Score still decrements once upon resume
2. If you like this jeopardy/mystical music playing while the hints are pressed down.... then perhaps we should decrement the score in smaller increments repeatedly every so many miliseconds?

3. I think that when the game is finished, if the score is below 0 it should reset to 0? I'm not really sure but I have a feeling that having negative scores could cause problems somewhere. Since we're using the leaderboard to keep track of the User's total xp, it will never go down anyway, because it will always retrieve the highest value ever recorded. If we switch to using firebase to keep track of user's xp then we could have it go down... At any rate to simplify things, having scores that never go below 0 might be a good idea.

**Comment by jfkonecn** [comment]
1.
I'm not having problems with the score decrementing for me on a resume. Are you using a saved game from before I made the change?

2.
Not a bad idea. I'll add it in.

3.
The only problems I could foresee with never allowing the score to be zero is that if a user goes below zero then two different situations could occur. The first would be that the score remains zero when they do something which should increase their points(because the score would normally be negative). The other situation is that the no matter negative the real score is, the score goes up if the score is zero. 

It might be less confusing to the user if we have the xp hard set to 0 for a negative score.

**Comment by Licktopia** [comment]
1. I just tested starting a Hard game which has score of 200, and immediatly saved the game with 4 seconds on the clock. I resumed the game and 4 seconds were on the clock on resuming but the score was 190. This is with the pulled changes. You can't actually see it decrement, it just has 10 points less than it should

3. I agree I was thinking just to make the adjustment when the game is over. Just if the final score is < 0, set it at 0, so when the score is submitted to the dbs and stuff it submits as 0. (Also the multiplier would amplify the negative score). I could also just check that on the UI end, I'm not sure what's the most correct thing to do.

**Comment by Licktopia** [comment]
Actually I think the score decrement problem has something to do with it not keeping proper track of the time on resume. You actually have to track the time when the clock is stopped and then when it starts again get that elapsed time (even if it's days) and make the proper adjustment. Because the score is decrementing every so many seconds while it's sitting around in saved state I think

**Comment by jfkonecn** [comment]
I think I fix it... The fix will only work on new saved game.

**Comment by Licktopia** [comment]
Thanks. Looks like an oversight on my part then. It seems fixed now.
